### ISSUE TITLE
Use CSS Grid

### ISSUE THREAD

**Issue by JacobHaig** [Erudition/Docket#8]
Change your Activity List styles to
> ul class="activity-list" style="display: grid;grid-auto-flow: dense;grid-template-columns: repeat(auto-fill, minmax( 100px, 1fr));grid-gap: 3px;"

This allows the activity-list to grow and expand dynamically to fill the screen. This also allows for dynamic grid-gaps 

The Result is this:
![image](https://user-images.githubusercontent.com/10782090/63031533-19d62000-be82-11e9-993f-33452871e9ea.png)

Vs current version
![image](https://user-images.githubusercontent.com/10782090/63031714-720d2200-be82-11e9-889a-db97b6989825.png)

**Comment by JacobHaig** [comment]
Create a PullRequest #9 . Check it out!

**Comment by Erudition** [comment]
Oh damn! I was definitely going to use grid but that whole page was probably gonna be scrapped anyway (hence why it's still so ugly) because I'm thinking of moving to NativeScript.
Thanks for the implementation though!

**Comment by Erudition** [comment]
Merged #9 (my first PR ever! :O ) that feels weird
Thanks Jacob, feel free to pretty it up some more :P
